#!/usr/bin/env python3
"""tools/hashgen.py -- generate compile-time DJB2 hashes for Wraith.

Reads `tools/api_list.txt` (one entry per line, lines starting with '#'
or blank are ignored). Lines ending in '.dll' are emitted as module
hashes; everything else is emitted as API-name hashes.

Output is a single C header with `#define WRAITH_H_<symbol> 0x........u`
constants. The generated header is consumed by the runtime resolver
under `WRAITH_USE_API_HASHING=ON`; off by default, so the binary still
ships even if the build host has no Python installed (we treat the
header as "best-effort" - the .c file uses fall-back computation when
absent).

The arithmetic MUST match src/stealth/hashing/hash_djb2.c exactly. If
you change one, change the other.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def djb2(s: str) -> int:
    """Case-insensitive DJB2 - mirror of fold_ascii in hash_djb2.c."""
    h = 5381
    for ch in s:
        c = ord(ch)
        if 0x41 <= c <= 0x5A:
            c += 0x20
        h = ((h << 5) + h + c) & 0xFFFFFFFF
    return h


def sanitize_symbol(name: str) -> str:
    return (name.replace(".", "_")
                .replace("-", "_")
                .replace("/", "_"))


def parse(input_path: Path) -> tuple[list[str], list[str]]:
    modules: list[str] = []
    apis: list[str] = []
    for raw in input_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.lower().endswith(".dll"):
            modules.append(line)
        else:
            apis.append(line)
    return modules, apis


def emit(modules: list[str], apis: list[str], out_path: Path) -> None:
    lines: list[str] = [
        "/*",
        " * wr_api_hashes.h - GENERATED by tools/hashgen.py.",
        " * DO NOT EDIT BY HAND. Regenerate by re-running CMake.",
        " *",
        " * The integers below are case-insensitive DJB2 hashes computed",
        " * with the same arithmetic as src/stealth/hashing/hash_djb2.c.",
        " */",
        "",
        "#ifndef WRAITH_API_HASHES_H",
        "#define WRAITH_API_HASHES_H",
        "",
        "#include <stdint.h>",
        "",
        "/* ===== Module name hashes (LDR walk keys) ===== */",
    ]
    for m in modules:
        sym = "WRAITH_H_" + sanitize_symbol(m)
        lines.append(f"#define {sym:<40s} 0x{djb2(m):08x}u")

    lines += [
        "",
        "/* ===== API name hashes (export-table search keys) ===== */",
    ]
    for a in apis:
        sym = "WRAITH_H_" + sanitize_symbol(a)
        lines.append(f"#define {sym:<40s} 0x{djb2(a):08x}u")

    lines += [
        "",
        f"#define WRAITH_HASH_MODULES_COUNT {len(modules)}u",
        f"#define WRAITH_HASH_APIS_COUNT    {len(apis)}u",
        "",
        "#endif /* WRAITH_API_HASHES_H */",
        "",
    ]

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--input",  required=True, type=Path,
                   help="path to api_list.txt")
    p.add_argument("--output", required=True, type=Path,
                   help="path to write generated wr_api_hashes.h")
    args = p.parse_args()

    modules, apis = parse(args.input)
    emit(modules, apis, args.output)
    print(f"hashgen: wrote {args.output} "
          f"({len(modules)} modules, {len(apis)} APIs)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
