# cmake/version.cmake
#
# Wraith semantic version. Update when tagging a release.

set(WRAITH_VERSION_MAJOR 1)
set(WRAITH_VERSION_MINOR 0)
set(WRAITH_VERSION_PATCH 0)
set(WRAITH_VERSION_PRERELEASE "")

if(WRAITH_VERSION_PRERELEASE)
  set(WRAITH_VERSION "${WRAITH_VERSION_MAJOR}.${WRAITH_VERSION_MINOR}.${WRAITH_VERSION_PATCH}-${WRAITH_VERSION_PRERELEASE}")
else()
  set(WRAITH_VERSION "${WRAITH_VERSION_MAJOR}.${WRAITH_VERSION_MINOR}.${WRAITH_VERSION_PATCH}")
endif()
